version: '3.2'
services:
  web-server:
    container_name: api-server
    build: ./api-module
    ports:
      - "8000:8000"
    environment:
      SPRING_DATABASE_URL: jdbc:mariadb://database:3306/nassafy  # 로컬에서 docker로 서버 띄워서 확인하고 싶을 때는 databse를 j8d106.p.ssafy.io로 변경, 코드 올릴 때는 database로 다시 변경
      SPRING_DATABASE_USERNAME: root
      SPRING_DATABASE_PASSWORD: ssafy1234!
      TZ: Asia/Seoul
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100000000"
    networks:
      D106-network:
        ipv4_address: 172.19.0.7
  batch-server:
    container_name: batch-server
    build: ./batch-module
    ports:
      - "8001:8001"
    environment:
      SPRING_DATABASE_URL: jdbc:mariadb://database:3306/nassafy  # 로컬에서 docker로 서버 띄워서 확인하고 싶을 때는 databse를 j8d106.p.ssafy.io로 변경, 코드 올릴 때는 database로 다시 변경
      SPRING_DATABASE_USERNAME: root
      SPRING_DATABASE_PASSWORD: ssafy1234!
      TZ: Asia/Seoul
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100000000"
    networks:
      D106-network:
        ipv4_address: 172.19.0.9

networks:
  aro-network:
    external: true